test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

<<<<<<< HEAD
# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
=======
# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
>>>>>>> 4892209c91d4f8e8df84de74ca3cbaa781bc3e85
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
<<<<<<< HEAD
#   bucket: your_own_bucket-<%= Rails.env %>
=======
#   bucket: your_own_bucket
>>>>>>> 4892209c91d4f8e8df84de74ca3cbaa781bc3e85

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
<<<<<<< HEAD
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
=======
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
>>>>>>> 4892209c91d4f8e8df84de74ca3cbaa781bc3e85
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
<<<<<<< HEAD
#   container: your_container_name-<%= Rails.env %>
=======
#   container: your_container_name
>>>>>>> 4892209c91d4f8e8df84de74ca3cbaa781bc3e85

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
